language: php

services:
  - postgresql
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

addons:
  postgresql: "9.4"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

env:
  - DB_TYPE=pgsql DB_DSN=pgsql:dbname=yii2_guzzle;host=localhost DB_USERNAME=postgres DB_PASSWORD=root
  - DB_TYPE=mysql DB_DSN=mysql:dbname=yii2_guzzle;host=localhost DB_USERNAME=root DB_PASSWORD=

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - sh -c "if [ '$DB_TYPE' = 'pgsql' ]; then psql -c 'CREATE DATABASE yii2_guzzle;' -U postgres; fi"
  - sh -c "if [ '$DB_TYPE' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS yii2_guzzle;'; fi"

script:
  - travis_retry composer lint
  - travis_retry composer cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
